// This file is "main.dart"
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

import 'package:e_commerce_app/data/model.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'home_model.freezed.dart';

@freezed
class ProductState with _$ProductState {
  const factory ProductState({
    @Default([])
    List<ECommerceModel> allProducts, // All products fetched from API
    @Default([])
    List<ECommerceModel>
        filteredProducts, // Filtered products based on category or search
    @Default('') String selectedCategory, // Currently selected category
    @Default('') String searchQuery, // Search input
    @Default(true) bool isLoading, // Indicates whether data is being loaded
    String? errorMessage, // Holds error message, if any
  }) = _ProductState;
}
